### ISSUE TITLE
Filteren bij componenten gaat mis met de "Alle" knop

### ISSUE THREAD

**Issue by matthiasoliveiro** [ConductionNL/love-common-ground#25]
Het filter alle doet niet wat ik verwacht.

Steps to reproduce:
-Ga naar componenten
-Klik op bronnen
-Klik op applicaties
-Klik op alle

Ik verwacht nu alle componenten weer te zien echter zie ik geen componenten

**Comment by rubenvdlinde** [comment]
Er gaat zowiezo ook een en ander fout in de regeltjes rondom de kleuren van applicaties etc
