### ISSUE TITLE
Meld aan linkje verwijst naar landings page

### ISSUE THREAD

**Issue by matthiasoliveiro** [ConductionNL/love-common-ground#34]
Zie ook bijgevoegd plaatje, hier is een "meld aan" linkje waar je zou verwachten dat je naar de inlog pagina gaat. Echter ga je naar de landingspage.

![image](https://user-images.githubusercontent.com/36506861/63781228-bddfb280-c8e9-11e9-828d-1bd32879c113.png)

**Comment by rubenvdlinde** [comment]
Euh ja, want aanmelden gaat via de landingspage?

Heb je anders een tekstje om dat te verduidelijken?

**Comment by rubenvdlinde** [comment]
Ik heb een tekst wijziging gedaan en door gelinkt naar het inlog formulier

**Comment by matthiasoliveiro** [comment]
Waarschijnlijk iets misgegaan in de deploy hij doet bij mij nog niets.
