### ISSUE TITLE
Foutje in de organisatie naam Den Bosh... dat moet waarschijnlijk 's-Hertogenbosch zijn

### ISSUE THREAD

**Issue by matthiasoliveiro** [ConductionNL/love-common-ground#52]
Zie het plaatje, het moet Den Bosch zijn of nog beter 's-Hertogenbosch.

![image](https://user-images.githubusercontent.com/36506861/64006963-9cfaa580-cb13-11e9-9313-70645bddb279.png)

**Comment by rubenvdlinde** [comment]
Fixed met prio

**Comment by matthiasoliveiro** [comment]
Is al beter maar nog niet helemaal goed.

![image](https://user-images.githubusercontent.com/36506861/64374478-41a14980-d024-11e9-82ee-afe82e32e1fe.png)
