### ISSUE TITLE
Readme en installation links gaan nergens naar toe

### ISSUE THREAD

**Issue by matthiasoliveiro** [ConductionNL/love-common-ground#53]
Readme en installation links gaan nergens naar toe. Ik vermoed dat dit naar de Readme.md zou moeten.

![image](https://user-images.githubusercontent.com/36506861/64374364-f8e99080-d023-11e9-82ed-b3f12659dd3e.png)

**Comment by rubenvdlinde** [comment]
Dit was een dubbele issue is nu opgepakt
