### ISSUE TITLE
Mouseover component tile zorgt niet voor een "klik handje"

### ISSUE THREAD

**Issue by matthiasoliveiro** [ConductionNL/love-common-ground#56]
Als je met je muis over een component tile heen gaat dan verschijnt er geen "klik handje" zo als bij organisaties. 

Fout situatie:
![WhatsApp Image 2019-09-21 at 09 23 06 (1)](https://user-images.githubusercontent.com/36506861/65369768-9c0bee00-dc51-11e9-8ef3-299f7eba3f4b.jpeg)

Gewenste situatie:
![WhatsApp Image 2019-09-21 at 09 23 06](https://user-images.githubusercontent.com/36506861/65369773-a4fcbf80-dc51-11e9-8d6e-9c6a7f0e7cc0.jpeg)

**Comment by matthiasoliveiro** [comment]
Het ziet er naar uit dat hierdoor de componenten helemaal niet klikbaar zijn op mobile devices

**Comment by rubenvdlinde** [comment]
Er is nu een mouseover handje toegevoegd met css, maar dat doet niks af aan of de componenten te bekijken zijn op een mobiele telefoon.
