### ISSUE TITLE
Readme en installatie links in het Component detail panel werken niet zo als verwacht

### ISSUE THREAD

**Issue by matthiasoliveiro** [ConductionNL/love-common-ground#57]
Zie ook het filmpje,
De readme en installatie linkjes doen niet wat we verwachten of op zo'n manier dat het niet duidelijk is voor de gebruiker dat het heeft gewerkt.

[Component detail page.zip](https://github.com/ConductionNL/love-common-ground/files/3638427/Component.detail.page.zip)

**Comment by rubenvdlinde** [comment]
Is gefixed met nieuw javascript
