### ISSUE TITLE
Common ground "spoor" foto maakt het menu onleesbaar.

### ISSUE THREAD

**Issue by matthiasoliveiro** [ConductionNL/love-common-ground#63]
Door de witte tekst op witte spoor bielzen is het niet echt goed leesbaar wat er nu staat.
Voorstel, schuif de tekst naar er boven.

![image](https://user-images.githubusercontent.com/36506861/65370625-581de680-dc5b-11e9-95c4-9ae6878b75fe.png)

**Comment by rubenvdlinde** [comment]
Nou die afbeelding hoort eigenlijk full srcreen te zijn, dat is nu gefixed maar dan is het gehele ding nog steeds pixelig en lelijk. Dus heb hem er nu zowiezo uitgehaald.
